### PR TITLE
chore: fix typo

### LINKED ISSUE #5: Fix typo in README.md and process-polyfill.js
**Describe the bug**
https://github.com/abiriadev/seia/blob/26278b9282a700e37fcfa4f8dae623e3ef9c2de4/README.md?plain=1#L35
https://github.com/abiriadev/seia/blob/26278b9282a700e37fcfa4f8dae623e3ef9c2de4/packages/seia/src/process-polyfill.ts#L6

**Expected behavior**
`They, install Seia:` in `README.md` should be `Then, install Seia:`.
`'prodection'` in `packages/seia/src/process-polyfill.ts` should be `'production'`.

### PR DESCRIPTION
**Pull request by nemorize**
fixes #5

### CODE REVIEW

**Comment by abiriadev** [comment]
@nemorize Would you change https://github.com/abiriadev/seia/blob/main/packages/seia/README.md too?

**Comment by abiriadev** [comment]
Or you can allow me to push additional commits: [GitHub doc](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by nemorize** [comment]
Oh, okay... wait for a minute 😊

**Comment by abiriadev** [comment]
Perfect! :+1:

**Pull request merged**
